from pydantic import BaseModel, Field

from schemas.analysis import PaperAnalysis


class ComparisonRequest(BaseModel):
    """Input for the comparison engine: a batch of already-analyzed papers.

    The minimum batch size (settings.COMPARISON_MIN_PAPERS, default 10) is
    enforced in services/comparison_service.py rather than here, since it's
    a runtime-configurable business rule rather than fixed shape validation.
    """

    analyses: list[PaperAnalysis] = Field(..., min_length=1)


class ComparisonTableRow(BaseModel):
    """One row of the side-by-side comparison table, one row per input paper."""

    title: str | None = None
    electrolyte: str | None = None
    cathode: str | None = None
    anode: str | None = None
    separator: str | None = None
    cell_type: str | None = None
    voltage_window: str | None = None
    temperature: str | None = None


class ComparisonResult(BaseModel):
    """Structured cross-paper comparison generated by the AI comparison engine."""

    paper_count: int
    common_experimental_conditions: list[str] = Field(default_factory=list)
    differences: list[str] = Field(default_factory=list)
    frequently_used_electrolytes: list[str] = Field(default_factory=list)
    frequently_used_additives: list[str] = Field(default_factory=list)
    most_common_cathode: str | None = None
    most_common_anode: str | None = None
    research_trend: str | None = None
    research_gap: str | None = None
    potential_future_direction: str | None = None
    comparison_table: list[ComparisonTableRow] = Field(default_factory=list)
